name: Update F1 Driver Standings

on:
  schedule:
    - cron: "0 */1 * * *"   # every 4 hours
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update standings
        run: node updateStandings.js

      - name: Commit and push if changed
        run: |
          git config user.name "f1-bot"
          git config user.email "f1-bot@users.noreply.github.com"
          git add f1_driver_standings.json
          git commit -m "Update F1 driver standings" || exit 0
          git push
